### ISSUE TITLE
Typical crashing issue

### ISSUE THREAD

**Issue by Raghav155221** [DeDiamondPro/Resourcify#36]
**Technical Information**
Resourcify version:1.40+beta
Minecraft version:1.20.1

**Describe the bug**
When i click the plus button it crashes i have not enough crashes mod and it says minecraft crashed so i came here to report the bug.

**Expected behavior**
I expected it to not crash.

**Steps to reproduce**
Open resource packs then click plus button

**Additional information**
[latestlog.txt](https://github.com/user-attachments/files/15721772/latestlog.txt)
Here is the crash log

**Comment by Raghav155221** [comment]
I forgot to add its a fabric minecraft version

**Comment by DeDiamondPro** [comment]
Hi, this is not an issue with Resourcify, and instead is probably an issue with Vulkan mod or maybe even Pojav launcher.
The root cause is this stack trace:
```
java.lang.NullPointerException: Cannot read field "width" because "net.vulkanmod.gl.GlTexture.boundTexture.vulkanImage" is null
	at net.vulkanmod.gl.GlTexture.texImage2D(GlTexture.java:52) ~[VulkanMod_1.20-0.3.4_V9.3_stable_arm64.jar:?]
	at com.mojang.blaze3d.platform.GlStateManager._texImage2D(GlStateManager.java:929) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.platform.TextureUtil.prepareImage(TextureUtil.java:77) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.platform.TextureUtil.prepareImage(TextureUtil.java:54) ~[client-intermediary.jar:?]
	at gg.essential.universal.utils.ReleasedDynamicTexture.uploadTexture(ReleasedDynamicTexture.kt:66) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at dev.dediamondpro.resourcify.libs.elementa.components.UIImage$2$1.invoke(UIImage.kt:62) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at dev.dediamondpro.resourcify.libs.elementa.components.UIImage$2$1.invoke(UIImage.kt:61) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at dev.dediamondpro.resourcify.libs.elementa.components.Window.doDraw(Window.kt:60) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at dev.dediamondpro.resourcify.libs.elementa.components.Window.draw(Window.kt:48) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at dev.dediamondpro.resourcify.libs.elementa.WindowScreen.onDrawScreen(WindowScreen.kt:60) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at dev.dediamondpro.resourcify.gui.PaginatedScreen.onDrawScreen(PaginatedScreen.kt:63) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at dev.dediamondpro.resourcify.gui.browsepage.BrowseScreen.onDrawScreen(BrowseScreen.kt:381) ~[Resourcify%20(1.20-1.20.1-fabric)-1.4.0+beta.1.jar:?]
	at gg.essential.universal.UScreen.onDrawScreen(UScreen.kt:291) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at gg.essential.universal.UScreen$onDrawScreenCompat$1.invoke(UScreen.kt:297) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at gg.essential.universal.UScreen$onDrawScreenCompat$1.invoke(UScreen.kt:295) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at gg.essential.universal.UMatrixStack$Compat.runLegacyMethod(UMatrixStack.kt:316) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at gg.essential.universal.UScreen.onDrawScreenCompat(UScreen.kt:295) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at gg.essential.universal.UScreen.method_25394(UScreen.kt:85) ~[universalcraft-337-75b92430607d7fc5.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.15.11-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
```
Which leads me to believe that it is an issue with Vulkan mod, since it is initially throwing the error.
If you are able to reproduce the issue without Vulkan mod, please feel free to reopen this issue so I can investigate the issue further.

**Comment by Raghav155221** [comment]
Ok thanks

**Comment by Versatile-V1** [comment]
@DeDiamondPro Vulkanmod has improved a lot over these years. So it would be great if you take another look at the compatibility between vulkanmod and resourcify.

**Comment by DeDiamondPro** [comment]
> [@DeDiamondPro](https://github.com/DeDiamondPro) Vulkanmod has improved a lot over these years. So it would be great if you take another look at the compatibility between vulkanmod and resourcify.

This issue and the more recent incompatibility between vulkanmod are unfortunately not related, and this incompatibility (since the release of 1.21.6) is not easy to solve. So since MC has announced they are porting to vulkan I probably won’t be adding support for the mod and will wait for Mojang to do their port and port to that. This issue comes from some of the libraries Resourcify uses (specifically elementa).

**Comment by Versatile-V1** [comment]
> > [@DeDiamondPro](https://github.com/DeDiamondPro) Vulkanmod has improved a lot over these years. So it would be great if you take another look at the compatibility between vulkanmod and resourcify.
> 
> This issue and the more recent incompatibility between vulkanmod are unfortunately not related, and this incompatibility (since the release of 1.21.6) is not easy to solve. So since MC has announced they are porting to vulkan I probably won’t be adding support for the mod and will wait for Mojang to do their port and port to that. This issue comes from some of the libraries Resourcify uses (specifically elementa).

Understood. But when Mojang switches to vulkan and if vulkanmod uses that rendering engine as a base like sodium does with the blaze3d engine right now wouldn't that make it possible to add support for vulkanmod as well in the future?

**Comment by DeDiamondPro** [comment]
> Understood. But when Mojang switches to vulkan and if vulkanmod uses that rendering engine as a base like sodium does with the blaze3d engine right now wouldn't that make it possible to add support for vulkanmod as well in the future?

Depends on how elementa/universalcraft decides to implement this support, but we’ll see.

**Comment by ShayBox** [comment]
Why is this mod marked incompatible with vulkan mod? it has nothing to do with rendering, it's just a resourcepack downloader...

**Comment by DeDiamondPro** [comment]
> Why is this mod marked incompatible with vulkan mod? it has nothing to do with rendering, it's just a resourcepack downloader...

As said repeatedly in this thread, this is because of how the gui lib (elementa) that Resourcify uses works.
